name: Docker Actions

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker
        run: docker build -t logger .
        
      - name: Run Docker image container
        run: |
          mkdir -p logs
          docker run -it -v "$(pwd)/logs/:/home/logs/" logger
          
      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
          
